// Generated by AI Collaborator - Universal Timezone Formatter
export function getSystemTimezone(): string {
  if (typeof window !== 'undefined') {
    try {
      const saved = localStorage.getItem('zecratary_timezone');
      if (saved && saved.trim()) return saved.trim();
      const userRaw = localStorage.getItem('zecratary_current_user') || localStorage.getItem('zecratary_user');
      if (userRaw) {
        const u = JSON.parse(userRaw);
        if (u.timezone || u.timeZone) return u.timezone || u.timeZone;
      }
    } catch (_) {}
  }
  try {
    return Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC';
  } catch (_) {
    return 'UTC';
  }
}

export function formatSystemTimestamp(
  dateInput: string | number | Date | null | undefined,
  options?: Intl.DateTimeFormatOptions,
  customTimezone?: string
): string {
  if (!dateInput) return '-';
  const tz = customTimezone || getSystemTimezone();
  try {
    const d = typeof dateInput === 'string' || typeof dateInput === 'number' ? new Date(dateInput) : dateInput;
    if (isNaN(d.getTime())) return String(dateInput);
    return new Intl.DateTimeFormat(undefined, {
      timeZone: tz,
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
      hour12: true,
      ...options
    }).format(d);
  } catch (_) {
    return new Date(dateInput).toLocaleString();
  }
}

export function formatSystemDate(
  dateInput: string | number | Date | null | undefined,
  customTimezone?: string
): string {
  return formatSystemTimestamp(dateInput, { hour: undefined, minute: undefined, second: undefined }, customTimezone);
}
